"""add strategy tables

Revision ID: a6f5d168726f
Revises: 003_add_post_platforms
Create Date: 2026-07-18 22:52:11.400031
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6f5d168726f'
down_revision: Union[str, None] = '003_add_post_platforms'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_provider_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', name='uq_workspace_platform')
    )
    op.create_index(op.f('ix_platform_provider_configs_workspace_id'), 'platform_provider_configs', ['workspace_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_audience', sa.String(length=300), nullable=True),
    sa.Column('additional_context', sa.Text(), nullable=True),
    sa.Column('brand_voice_id', sa.String(), nullable=True),
    sa.Column('generated_texts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_prompts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brand_voice_id'], ['brand_voices.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_platform'), 'content_items', ['platform'], unique=False)
    op.create_index(op.f('ix_content_items_status'), 'content_items', ['status'], unique=False)
    op.create_index(op.f('ix_content_items_workspace_id'), 'content_items', ['workspace_id'], unique=False)
    op.create_table('platform_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_posts_content_item_id'), 'platform_posts', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_platform_posts_platform'), 'platform_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_posts_platform_post_id'), 'platform_posts', ['platform_post_id'], unique=False)
    op.create_table('platform_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('engagements', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('stored_as_embedding', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['platform_post_id'], ['platform_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_analytics_platform_post_id'), 'platform_analytics', ['platform_post_id'], unique=False)
    op.drop_index(op.f('ix_post_platforms_platform'), table_name='post_platforms')
    op.drop_index(op.f('ix_post_platforms_post_id'), table_name='post_platforms')
    op.drop_index(op.f('ix_post_platforms_status'), table_name='post_platforms')
    op.drop_index(op.f('ix_post_platforms_workspace_id'), table_name='post_platforms')
    op.drop_index(op.f('uq_post_platform'), table_name='post_platforms')
    op.drop_table('post_platforms')
    op.drop_index(op.f('ix_posts_platform'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_workspace_id'), table_name='posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_workspace_id'), 'posts', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_platform'), 'posts', ['platform'], unique=False)
    op.create_table('post_platforms',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_asset_ids', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('platform_post_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('token_version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_platforms_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('post_platforms_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_platforms_pkey'))
    )
    op.create_index(op.f('uq_post_platform'), 'post_platforms', ['post_id', 'platform'], unique=True)
    op.create_index(op.f('ix_post_platforms_workspace_id'), 'post_platforms', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_post_platforms_status'), 'post_platforms', ['status'], unique=False)
    op.create_index(op.f('ix_post_platforms_post_id'), 'post_platforms', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_platforms_platform'), 'post_platforms', ['platform'], unique=False)
    op.drop_index(op.f('ix_platform_analytics_platform_post_id'), table_name='platform_analytics')
    op.drop_table('platform_analytics')
    op.drop_index(op.f('ix_platform_posts_platform_post_id'), table_name='platform_posts')
    op.drop_index(op.f('ix_platform_posts_platform'), table_name='platform_posts')
    op.drop_index(op.f('ix_platform_posts_content_item_id'), table_name='platform_posts')
    op.drop_table('platform_posts')
    op.drop_index(op.f('ix_content_items_workspace_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_status'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_platform'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_platform_provider_configs_workspace_id'), table_name='platform_provider_configs')
    op.drop_table('platform_provider_configs')
    # ### end Alembic commands ###
