"""Pydantic V2 schemas for AI workflow pipeline."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Enums ──────────────────────────────────────────────────────────────────

class PlatformType(str, Enum):
    LINKEDIN = "linkedin"
    TWITTER = "twitter"
    INSTAGRAM = "instagram"
    FACEBOOK = "facebook"
    YOUTUBE = "youtube"


class ContentStatus(str, Enum):
    IDEATION = "ideation"
    RESEARCH = "research"
    DRAFTING = "drafting"
    VISUAL_PROMPT = "visual_prompt"
    SAVED_TO_DB = "saved_to_db"
    PENDING_APPROVAL = "pending_approval"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    FAILED = "failed"


class AIProvider(str, Enum):
    CLAUDE = "claude"
    OPENAI = "openai"
    GEMINI = "gemini"
    OPENROUTER = "openrouter"
    OMNIROUTE = "omniroute"


# ── Content Idea (input) ──────────────────────────────────────────────────

class ContentIdeaRequest(BaseModel):
    """Incoming request to trigger the AI content workflow."""
    topic: str = Field(..., min_length=1, max_length=500, description="Topic or theme for content generation")
    platform: PlatformType = Field(..., description="Target social platform")
    provider_override: Optional[AIProvider] = Field(
        None,
        description="Force a specific AI provider for this request. "
                    "If omitted, the workspace-level config (set via UI) is used.",
    )
    brand_voice_id: Optional[str] = Field(None, description="Optional brand voice ID for tone alignment")
    target_audience: Optional[str] = Field(None, max_length=300, description="Target audience description")
    additional_context: Optional[str] = Field(None, max_length=1000, description="Extra instructions or context")


# ── Generated Post (output / intermediate) ─────────────────────────────────

class GeneratedText(BaseModel):
    """Text content generated by an AI provider."""
    provider: AIProvider
    model: str
    content: str
    tokens_used: int = 0


class VisualPrompt(BaseModel):
    """Image/video generation prompt produced during visual asset stage."""
    prompt_text: str
    style: Optional[str] = None
    aspect_ratio: str = "1:1"
    provider: AIProvider = AIProvider.OPENAI


class ContentItemResponse(BaseModel):
    """Representation of a content item flowing through the pipeline."""
    id: str
    topic: str
    platform: PlatformType
    status: ContentStatus
    generated_texts: list[GeneratedText] = []
    visual_prompts: list[VisualPrompt] = []
    final_text: Optional[str] = None
    created_at: datetime
    updated_at: datetime


class PostApprovalRequest(BaseModel):
    """HITL approval payload — moves post to SCHEDULED."""
    scheduled_at: Optional[datetime] = Field(None, description="When to publish; None = queue for next slot")
    override_text: Optional[str] = Field(None, max_length=5000, description="Optional text override before scheduling")


# ── Analytics ──────────────────────────────────────────────────────────────

class AnalyticsIngestRequest(BaseModel):
    """Raw daily stats from a platform for a single post."""
    platform_post_id: str = Field(..., description="Platform-native post ID")
    platform: PlatformType
    impressions: int = Field(0, ge=0)
    engagements: int = Field(0, ge=0)
    shares: int = Field(0, ge=0)
    clicks: int = Field(0, ge=0)
    likes: int = Field(0, ge=0)
    comments: int = Field(0, ge=0)
    reach: int = Field(0, ge=0)
    recorded_at: datetime = Field(default_factory=datetime.utcnow)


class PerformanceScoreResponse(BaseModel):
    """Output of the analytics feedback loop."""
    platform_post_id: str
    performance_score: float = Field(..., description="Normalized 0–10 score")
    stored_as_embedding: bool = Field(False, description="True if score > 7.5 and embedding was stored")
    breakdown: dict[str, float] = {}


class WorkflowTriggerResponse(BaseModel):
    """Response after triggering the content workflow."""
    content_item_id: str
    status: ContentStatus
    message: str


# ── Provider Config (UI settings) ─────────────────────────────────────────

class ProviderConfigCreate(BaseModel):
    """Set the AI provider for a specific platform within a workspace."""
    platform: PlatformType
    provider: AIProvider
    model: Optional[str] = Field(None, description="Optional model override (e.g. gpt-4o-mini)")


class ProviderConfigUpdate(BaseModel):
    """Update an existing provider config."""
    provider: Optional[AIProvider] = None
    model: Optional[str] = None
    is_active: Optional[bool] = None


class ProviderConfigResponse(BaseModel):
    """Returned provider config for a platform."""
    id: str
    workspace_id: str
    platform: PlatformType
    provider: AIProvider
    model: Optional[str] = None
    is_active: bool = True
    created_at: datetime
    updated_at: Optional[datetime] = None


class ProviderConfigBulkResponse(BaseModel):
    """All provider configs for a workspace."""
    workspace_id: str
    configs: list[ProviderConfigResponse]
